### ISSUE TITLE
Uncaught typeError: cannot read property 'type' of undefined at line 217

### ISSUE THREAD

**Issue by sid22m** [djaodjin/djaodjin-annotate#15]
Sometimes I get this error during redo. I am not able to find out in which case this happens

**Comment by StephaneRob** [comment]
This error can occur when there is nothing to redo. In test.html if nothing to redo the "redo" button is disabled.

**Comment by sid22m** [comment]
Steps to reproduce the issue (in test.html):
Edit image as u like using undo and redo.Then, 
Open console ->

1.  (This will remove all components so that we can initiate the plugin programmtically) --
    $("#myCanvas").remove();
    $("#annotate_tools").remove();
    $("#input_text").remove();

2. (This will re create all components) --
    var canvasDiv = document.createElement('div');
     canvasDiv.id = "myCanvas";
     document.body.appendChild(canvasDiv);

3. (Initiate the plugin again) --
  $('#myCanvas').annotate({color: 'blue', bootstrap: true, img: 'images/test.jpg'})

4. Now edit image using undo and redo. This error generates: 
Uncaught typeError: cannot read property 'type' of undefined at line 217

**Comment by smirolo** [comment]
Merged commit 3925ac26. Thank you very much for the report. It really helps making things better.
