### ISSUE TITLE
Working with multiple images , is it possible? how?

### ISSUE THREAD

**Issue by sid22m** [djaodjin/djaodjin-annotate#18]
I would like to use this tool to annotate multiple images. Now suppose i initialize this tool with first image and annotate that image and save that image. Now I initialize the tool with another image after destroying the first one. Now if i happen to annotate the saved first image again following the same steps . Can i make undo and redo work from the start if image already have some annotations??

**Comment by StephaneRob** [comment]
If you save an annotated image (saved with annotations) and reopen it to annotate it again you will be able to make undo/redo only on new annotations, old annotations are part of the image and not of the drawing canvas.
Let me know if it helps

**Comment by sid22m** [comment]
Yeah I am working on  a project where user can switch between different images and annotate them as he like. The only way i can think of is hiding the canvas and tool associated with the image user is not editing and showing them only when he switches to that image. This way annotations will be saved. If you think of any other way of doing this, please inform me , i will be greatly thankful.

**Comment by smirolo** [comment]
Isn't it possible to create two divs (one per image), associate an ``annotate`` to each div and use css display:none to switch between divs/images?

**Comment by StephaneRob** [comment]
I'm going to push an update to add ability to edit multiple images with one div.

**Comment by sid22m** [comment]
@StephaneRob Thanks man for adding ability to annotate multiple images. But it works only if i provide the url of multiple images during initialization. Here's my situation : I setup the tool with one initial image , say images/test.jpg. Later some point I download an image from external server in form of base64 string. Now I want to annotate this new image as well as edit annotations of my initial image. I can append the html for this new image but it will not work because during initialization i gave path of only test.jpg. How can i do this?? I will be greatly thankful

**Comment by StephaneRob** [comment]
@sid22m I'm going to add ability to push new images after initialization.

**Comment by StephaneRob** [comment]
@sid22m Pushed (#20). After initialisation is now possible to add an image like this:

```javascript
$("#myCanvas").annotate("push", "images/image2.jpg");
```
Let me know if there is any issue.

**Comment by StephaneRob** [comment]
Fixed #20
