### ISSUE TITLE
Feature Request - Mobile Device Support

### ISSUE THREAD

**Issue by krishna711** [djaodjin/djaodjin-annotate#27]
Thanks Stephane for wonderful clean script. I really appreciate if you could add support for mobile device. We need it to include in one of project where mobile device usage is crucial. 

Thanks for your support.
Krishna

**Comment by StephaneRob** [comment]
@krishna711 a commit was merged to support mobile device.
Please, let me know if any issues.

**Comment by krishna711** [comment]
Thanks Stephane, It works.. One issue we are facing now. By default rectangle control is enabled which make us unable to enlarge image on mobile device. It should be disabled by default when we click on it then it should start working..

**Comment by StephaneRob** [comment]
Fixed #28 and #29
