### ISSUE TITLE
Not working after destroying.

### ISSUE THREAD

**Issue by sid22m** [djaodjin/djaodjin-annotate#32]
Jsfiddle : http://jsfiddle.net/1Lf9htL5/10/
Steps to reproduce the issue:
1.  Push new image.
2. Destroy the tool.
3. Push new image again.
4. Switch images. I get an error : ``Uncaught TypeError: Cannot read property 'path' of undefined``

**Comment by StephaneRob** [comment]
thanks @sid22m for reporting this issue. I pushed a fix 01f7ed389ff8d09331441cf07b04603e81d8012e and release a new version (v0.0.4) for bower.

Let me know if everything work as expected.

**Comment by sid22m** [comment]
Thanks @StephaneRob .It is working now
