### ISSUE TITLE
Demo broken locally and features

### ISSUE THREAD

**Issue by jasondavis** [djaodjin/djaodjin-annotate#35]
When I install locally I cannot seem to get any of the tools to work on my canvas.  The demo in this repo, the only tool that sort of works is the text tool and it lets me enter text but as soon as focus is lost from the text input, it disappears from view.  The other tools when applied to the canvas do not show up at all for me.

I tried in Firefox, Chrome, and IE.

The demo on the website linked here does work for me though and based on that demo,

Couple questions based on my usage of the demo site:

- Is it possibble to click a and drag to re-position any items?  
- Is it possibble to click and delete an item, beside from using the undo tool?  
- I know you can set the color, line thickness, etc from the JS object options.  Would it be possibble to update these dynamically as well?  For example if I build a selection element for color and line thickness for user to select and use an onchange event, can I call a function in this library to set those new values after the library has been initiated already?  

Thanks for any help.  I am trying to add basic annotation tools to my screenshot chrome extension.  User can create a selection area/cropped screenshot now and then I want to use this libraruy to allow them to edit it before it is uploaded to server.

**Comment by smirolo** [comment]
Thanks for the detail report @jasondavis. I will look at why the in-repo demo is broken over the week-end. Stay tuned.

Though we have tried to keep the annotate tool as simple as possible for the use case of reporting UX issues on a webpage, some of your suggestions sound really good. If you are interested to create a pull request, I will merge it.

**Comment by smirolo** [comment]
Hi  @jasondavis. I added the missing bootstrap vendor files. Opening test.html locally on my machine now enables annotation of the image. I also added 3 separate issues (#36, #37, #38) to track the features you proposed here. Thanks again for the report!
